export interface SystemColorDefinition {
  key: string;
  name: string;
  hexCode: string;
}

export const SYSTEM_COLORS: readonly SystemColorDefinition[] = [
  { key: 'system:red', name: 'Red', hexCode: '#EF4444' },
  { key: 'system:maroon', name: 'Maroon', hexCode: '#7F1D1D' },
  { key: 'system:pink', name: 'Pink', hexCode: '#EC4899' },
  { key: 'system:rose', name: 'Rose', hexCode: '#F43F5E' },
  { key: 'system:orange', name: 'Orange', hexCode: '#F97316' },
  { key: 'system:gold', name: 'Gold', hexCode: '#EAB308' },
  { key: 'system:yellow', name: 'Yellow', hexCode: '#FACC15' },
  { key: 'system:green', name: 'Green', hexCode: '#22C55E' },
  { key: 'system:teal', name: 'Teal', hexCode: '#14B8A6' },
  { key: 'system:cyan', name: 'Cyan', hexCode: '#06B6D4' },
  { key: 'system:blue', name: 'Blue', hexCode: '#3B82F6' },
  { key: 'system:navy', name: 'Navy', hexCode: '#1E3A5F' },
  { key: 'system:indigo', name: 'Indigo', hexCode: '#6366F1' },
  { key: 'system:purple', name: 'Purple', hexCode: '#A855F7' },
  { key: 'system:violet', name: 'Violet', hexCode: '#8B5CF6' },
  { key: 'system:magenta', name: 'Magenta', hexCode: '#D946EF' },
  { key: 'system:brown', name: 'Brown', hexCode: '#92400E' },
  { key: 'system:beige', name: 'Beige', hexCode: '#D4A574' },
  { key: 'system:cream', name: 'Cream', hexCode: '#FFFDD0' },
  { key: 'system:ivory', name: 'Ivory', hexCode: '#FFFFF0' },
  { key: 'system:white', name: 'White', hexCode: '#FFFFFF' },
  { key: 'system:off-white', name: 'Off-White', hexCode: '#FAF9F6' },
  { key: 'system:silver', name: 'Silver', hexCode: '#C0C0C0' },
  { key: 'system:grey', name: 'Grey', hexCode: '#6B7280' },
  { key: 'system:charcoal', name: 'Charcoal', hexCode: '#374151' },
  { key: 'system:black', name: 'Black', hexCode: '#000000' },
  { key: 'system:peach', name: 'Peach', hexCode: '#FFDAB9' },
  { key: 'system:coral', name: 'Coral', hexCode: '#FF7F50' },
  { key: 'system:salmon', name: 'Salmon', hexCode: '#FA8072' },
  { key: 'system:burgundy', name: 'Burgundy', hexCode: '#800020' },
  { key: 'system:wine', name: 'Wine', hexCode: '#722F37' },
  { key: 'system:rust', name: 'Rust', hexCode: '#B7410E' },
  { key: 'system:copper', name: 'Copper', hexCode: '#B87333' },
  { key: 'system:bronze', name: 'Bronze', hexCode: '#CD7F32' },
  { key: 'system:olive', name: 'Olive', hexCode: '#808000' },
  { key: 'system:mint', name: 'Mint', hexCode: '#98FF98' },
  { key: 'system:lavender', name: 'Lavender', hexCode: '#E6E6FA' },
  { key: 'system:lilac', name: 'Lilac', hexCode: '#C8A2C8' },
  { key: 'system:sky-blue', name: 'Sky Blue', hexCode: '#87CEEB' },
  { key: 'system:baby-pink', name: 'Baby Pink', hexCode: '#F4C2C2' },
  { key: 'system:multi-color', name: 'Multi-Color', hexCode: '#8B5CF6' },
];
