'use client';

import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { format } from 'date-fns';
import { ArrowLeft, CalendarDays, Mail, MapPin, MessageSquarePlus, Phone, Plus, ShieldCheck, Tag, UserRound } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Skeleton } from '@/components/ui/skeleton';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { useStoreSettings } from '../../settings/hooks/use-settings';
import {
  useAddAddress, useAddIdentity, useAddNote, useArchiveCustomer, useAssignCustomerTag,
  useCreateCustomerTag, useCustomer, useCustomerTags, useRecordConsent,
  useRemoveCustomerTag, useSetPrimaryIdentity, useUpdateCustomer,
} from '../hooks/use-customers';

type DialogName = 'profile' | 'identity' | 'address' | 'note' | 'tag' | 'consent' | null;

export default function CustomerProfilePage() {
  const router = useRouter();
  const { id } = useParams() as { id: string };
  const { data: response, isLoading, isError } = useCustomer(id);
  const { data: settingsResponse } = useStoreSettings();
  const { data: tagsResponse } = useCustomerTags();
  const [dialog, setDialog] = useState<DialogName>(null);
  const [archiveOpen, setArchiveOpen] = useState(false);
  const update = useUpdateCustomer();
  const archive = useArchiveCustomer();
  const addIdentity = useAddIdentity();
  const setPrimary = useSetPrimaryIdentity();
  const addAddress = useAddAddress();
  const addNote = useAddNote();
  const assignTag = useAssignCustomerTag();
  const removeTag = useRemoveCustomerTag();
  const createTag = useCreateCustomerTag();
  const recordConsent = useRecordConsent();
  const customer = response?.data;
  const tags = tagsResponse?.data ?? [];
  const currency = settingsResponse?.data.currencyCode || 'BDT';
  const money = (amount: number) => new Intl.NumberFormat('en-BD', { style: 'currency', currency, maximumFractionDigits: 0 }).format(amount / 100);

  if (isLoading) return <main className="flex flex-col gap-5 p-4 md:p-8"><Skeleton className="h-12 w-80" /><Skeleton className="h-40 w-full" /><Skeleton className="h-96 w-full" /></main>;
  if (isError || !customer) return <main className="p-8"><Alert variant="destructive"><AlertTitle>Customer unavailable</AlertTitle><AlertDescription>The profile may have been merged, anonymized, or removed.</AlertDescription></Alert></main>;

  const closeOnSuccess = { onSuccess: () => setDialog(null) };
  const submitProfile = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    update.mutate({ id, payload: { fullName: String(form.get('fullName')), status: String(form.get('status')) as typeof customer.status, preferredContactChannel: String(form.get('channel')) as typeof customer.preferredContactChannel, preferredLocale: String(form.get('locale')), source: String(form.get('source')) || undefined } }, closeOnSuccess);
  };
  const submitIdentity = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); addIdentity.mutate({ id, kind: String(form.get('kind')) as 'phone' | 'email', value: String(form.get('value')) }, closeOnSuccess); };
  const submitAddress = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); addAddress.mutate({ id, payload: { kind: String(form.get('kind')) as 'delivery' | 'billing' | 'other', label: String(form.get('label')) || undefined, recipientName: String(form.get('recipientName')) || undefined, phone: String(form.get('phone')) || undefined, addressLine1: String(form.get('addressLine1')), area: String(form.get('area')) || undefined, city: String(form.get('city')) || undefined, state: String(form.get('state')) || undefined, postalCode: String(form.get('postalCode')) || undefined, country: 'BD', isDefault: form.get('isDefault') === 'on' } }, closeOnSuccess); };
  const submitNote = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); addNote.mutate({ id, body: String(form.get('body')), isPinned: form.get('isPinned') === 'on' }, closeOnSuccess); };
  const submitConsent = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); recordConsent.mutate({ id, purpose: String(form.get('purpose')), channel: String(form.get('channel')), granted: form.get('granted') === 'true', source: String(form.get('source')) }, closeOnSuccess); };
  const submitTag = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const tagId = String(form.get('tagId') ?? ''); const newName = String(form.get('newTag') ?? '').trim(); if (tagId) assignTag.mutate({ id, tagId }, closeOnSuccess); else if (newName) createTag.mutate({ name: newName }, { onSuccess: (result) => { const created = (result as { data?: { id?: string } })?.data; if (created?.id) assignTag.mutate({ id, tagId: created.id }, closeOnSuccess); } }); };

  return (
    <main className="flex flex-1 flex-col gap-6 ">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
        <div className="flex items-start gap-4"><Button variant="outline" size="icon" onClick={() => router.push('/dashboard/customers')} aria-label="Back to customers"><ArrowLeft /></Button><Avatar className="size-12"><AvatarFallback>{customer.fullName.split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase()}</AvatarFallback></Avatar><div className="flex flex-col gap-2"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold tracking-tight">{customer.fullName}</h1><Badge variant={customer.status === 'active' ? 'secondary' : 'outline'}>{customer.status}</Badge>{customer.account ? <Badge variant="outline">Account {customer.account.status}</Badge> : <Badge variant="outline">No login account</Badge>}</div><p className="text-sm text-muted-foreground">Customer since {format(new Date(customer.createdAt), 'dd MMM yyyy')} · Preferred: {customer.preferredContactChannel}</p><div className="flex flex-wrap gap-1">{customer.tags.map((tag) => <Badge key={tag.id} variant="outline">{tag.name}<button type="button" className="ml-1" onClick={() => removeTag.mutate({ id, tagId: tag.id })} aria-label={`Remove ${tag.name}`}>×</button></Badge>)}</div></div></div>
        <div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setDialog('tag')}><Tag data-icon="inline-start" />Tag</Button><Button variant="outline" onClick={() => setDialog('note')}><MessageSquarePlus data-icon="inline-start" />Add note</Button><Button onClick={() => setDialog('profile')}>Edit profile</Button></div>
      </header>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Card><CardHeader><CardDescription>Bookings</CardDescription><CardTitle>{customer.totalBookings}</CardTitle></CardHeader></Card>
        <Card><CardHeader><CardDescription>Lifetime paid</CardDescription><CardTitle>{money(customer.totalSpent)}</CardTitle></CardHeader></Card>
        <Card><CardHeader><CardDescription>Last booking</CardDescription><CardTitle className="text-lg">{customer.lastBookingAt ? format(new Date(customer.lastBookingAt), 'dd MMM yyyy') : 'Never'}</CardTitle></CardHeader></Card>
        <Card><CardHeader><CardDescription>Account readiness</CardDescription><CardTitle className="text-lg">{customer.primaryPhone || customer.primaryEmail ? customer.account ? 'Enabled' : 'Ready to invite' : 'Contact required'}</CardTitle></CardHeader></Card>
      </section>

      {customer.status === 'blocked' ? <Alert variant="destructive"><ShieldCheck /><AlertTitle>Booking blocked</AlertTitle><AlertDescription>This customer cannot create a booking until their profile status is restored to active.</AlertDescription></Alert> : null}

      <Tabs defaultValue="overview" className="flex flex-col gap-4">
        <TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="bookings">Bookings ({customer.totalBookingCount})</TabsTrigger><TabsTrigger value="notes">Notes ({customer.notes.length})</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="privacy">Consent & privacy</TabsTrigger></TabsList>

        <TabsContent value="overview" className="grid gap-4 lg:grid-cols-2">
          <Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Contact identities</CardTitle><CardDescription>Verified or primary ways to identify this customer.</CardDescription></div><Button size="sm" variant="outline" onClick={() => setDialog('identity')}><Plus data-icon="inline-start" />Add</Button></CardHeader><CardContent className="flex flex-col gap-3">{customer.identities.map((identity) => <div key={identity.id} className="flex items-center justify-between gap-3 rounded-md border p-3"><div className="flex items-center gap-3">{identity.kind === 'phone' ? <Phone className="size-4 text-muted-foreground" /> : <Mail className="size-4 text-muted-foreground" />}<div><p>{identity.value}</p><p className="text-xs text-muted-foreground">{identity.kind}{identity.verifiedAt ? ' · verified' : ' · unverified'}</p></div></div>{identity.isPrimary ? <Badge>Primary</Badge> : <Button size="sm" variant="ghost" onClick={() => setPrimary.mutate({ id, identityId: identity.id })}>Make primary</Button>}</div>)}</CardContent></Card>
          <Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Addresses</CardTitle><CardDescription>Saved delivery and billing destinations.</CardDescription></div><Button size="sm" variant="outline" onClick={() => setDialog('address')}><Plus data-icon="inline-start" />Add</Button></CardHeader><CardContent className="flex flex-col gap-3">{customer.addresses.length ? customer.addresses.map((address) => <div key={address.id} className="flex items-start gap-3 rounded-md border p-3"><MapPin className="mt-1 size-4 text-muted-foreground" /><div className="flex flex-1 flex-col gap-1"><div className="flex flex-wrap gap-2"><span className="font-medium">{address.label || address.kind}</span>{address.isDefault ? <Badge variant="secondary">Default</Badge> : null}</div><p className="text-sm">{[address.addressLine1, address.addressLine2, address.area, address.city, address.state, address.postalCode].filter(Boolean).join(', ')}</p>{address.instructions ? <p className="text-xs text-muted-foreground">{address.instructions}</p> : null}</div></div>) : <p className="text-sm text-muted-foreground">No address has been saved.</p>}</CardContent></Card>
          <Card><CardHeader><CardTitle>Profile preferences</CardTitle></CardHeader><CardContent className="grid gap-3 text-sm sm:grid-cols-2"><div><p className="text-muted-foreground">Contact channel</p><p className="capitalize">{customer.preferredContactChannel}</p></div><div><p className="text-muted-foreground">Locale</p><p>{customer.preferredLocale}</p></div><div><p className="text-muted-foreground">Source</p><p>{customer.source || 'Unknown'}</p></div><div><p className="text-muted-foreground">Account</p><p>{customer.account?.status || 'Not invited'}</p></div></CardContent></Card>
        </TabsContent>

        <TabsContent value="bookings"><Card><CardHeader><CardTitle>Rental history</CardTitle><CardDescription>Bookings retain their own frozen delivery and pricing snapshots.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{customer.bookings.length ? customer.bookings.map((booking) => <Link key={booking.id} href={`/dashboard/bookings/${booking.id}`} className="flex flex-col gap-3 rounded-md border p-4 hover:bg-muted/50 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><CalendarDays className="size-4 text-muted-foreground" /><div><p className="font-medium">{booking.bookingNumber}</p><p className="text-xs text-muted-foreground">{booking.items.map((item) => item.productName).join(', ') || 'No items'}</p></div></div><div className="flex items-center gap-3"><Badge variant="outline">{booking.status}</Badge><span className="font-medium">{money(booking.grandTotal)}</span></div></Link>) : <p className="text-sm text-muted-foreground">No bookings yet.</p>}</CardContent></Card></TabsContent>

        <TabsContent value="notes"><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Internal notes</CardTitle><CardDescription>Append-only staff context; new notes do not rewrite history.</CardDescription></div><Button size="sm" onClick={() => setDialog('note')}><Plus data-icon="inline-start" />Add note</Button></CardHeader><CardContent className="flex flex-col gap-3">{customer.notes.map((note) => <div key={note.id} className="rounded-md border p-4"><div className="mb-2 flex items-center justify-between gap-3">{note.isPinned ? <Badge>Important</Badge> : <span />}<span className="text-xs text-muted-foreground">{format(new Date(note.createdAt), 'dd MMM yyyy, p')}</span></div><p className="whitespace-pre-wrap text-sm">{note.body}</p></div>)}</CardContent></Card></TabsContent>

        <TabsContent value="timeline"><Card><CardHeader><CardTitle>Operational timeline</CardTitle><CardDescription>Customer changes and commercial events in reverse chronological order.</CardDescription></CardHeader><CardContent className="flex flex-col gap-0">{customer.events.map((event, index) => <div key={event.id} className="flex gap-4"><div className="flex flex-col items-center"><span className="mt-1 size-2 rounded-full bg-primary" />{index < customer.events.length - 1 ? <span className="h-full w-px bg-border" /> : null}</div><div className="pb-5"><p className="font-medium">{event.summary}</p><p className="text-xs text-muted-foreground">{format(new Date(event.occurredAt), 'dd MMM yyyy, p')} · {event.type.replaceAll('_', ' ')}</p></div></div>)}</CardContent></Card></TabsContent>

        <TabsContent value="privacy" className="grid gap-4 lg:grid-cols-2"><Card><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Consent ledger</CardTitle><CardDescription>Every grant or revocation is retained with source and time.</CardDescription></div><Button size="sm" variant="outline" onClick={() => setDialog('consent')}>Record</Button></CardHeader><CardContent className="flex flex-col gap-3">{customer.consents.map((consent) => <div key={consent.id} className="flex items-center justify-between gap-3 rounded-md border p-3"><div><p className="font-medium">{consent.purpose}</p><p className="text-xs text-muted-foreground">{consent.channel || 'all channels'} · {consent.source} · {format(new Date(consent.recordedAt), 'dd MMM yyyy')}</p></div><Badge variant={consent.granted ? 'secondary' : 'outline'}>{consent.granted ? 'Granted' : 'Revoked'}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Privacy actions</CardTitle><CardDescription>Archiving stops normal use; anonymization is available through the protected privacy API when retention rules permit.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Alert><UserRound /><AlertTitle>Booking records are retained</AlertTitle><AlertDescription>Customer profile changes never rewrite the historical contact and delivery snapshots stored on bookings.</AlertDescription></Alert><Separator /><Button variant="destructive" onClick={() => setArchiveOpen(true)} disabled={customer.status === 'archived'}>Archive customer</Button></CardContent></Card></TabsContent>
      </Tabs>

      <Dialog open={dialog === 'profile'} onOpenChange={(open) => setDialog(open ? 'profile' : null)}><DialogContent><DialogHeader><DialogTitle>Edit customer profile</DialogTitle><DialogDescription>Contact identities and addresses are managed separately to preserve identity history.</DialogDescription></DialogHeader><form onSubmit={submitProfile} className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="profile-name">Full name</Label><Input id="profile-name" name="fullName" defaultValue={customer.fullName} required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label>Status</Label><Select name="status" defaultValue={customer.status}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="active">Active</SelectItem><SelectItem value="blocked">Blocked</SelectItem><SelectItem value="archived">Archived</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Preferred channel</Label><Select name="channel" defaultValue={customer.preferredContactChannel}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{['phone','sms','whatsapp','email'].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor="profile-locale">Locale</Label><Input id="profile-locale" name="locale" defaultValue={customer.preferredLocale} /></div><div className="flex flex-col gap-2"><Label htmlFor="profile-source">Source</Label><Input id="profile-source" name="source" defaultValue={customer.source ?? ''} /></div></div><DialogFooter><Button type="submit" disabled={update.isPending}>Save profile</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={dialog === 'identity'} onOpenChange={(open) => setDialog(open ? 'identity' : null)}><DialogContent><DialogHeader><DialogTitle>Add contact identity</DialogTitle><DialogDescription>The normalized value must be unique within this business.</DialogDescription></DialogHeader><form onSubmit={submitIdentity} className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label>Type</Label><Select name="kind" defaultValue="phone"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="phone">Phone</SelectItem><SelectItem value="email">Email</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor="identity-value">Phone or email</Label><Input id="identity-value" name="value" required /></div><DialogFooter><Button type="submit" disabled={addIdentity.isPending}>Add contact</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={dialog === 'address'} onOpenChange={(open) => setDialog(open ? 'address' : null)}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Add saved address</DialogTitle><DialogDescription>Booking checkout can reuse this address without changing earlier booking snapshots.</DialogDescription></DialogHeader><form onSubmit={submitAddress} className="flex flex-col gap-4"><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label>Type</Label><Select name="kind" defaultValue="delivery"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="delivery">Delivery</SelectItem><SelectItem value="billing">Billing</SelectItem><SelectItem value="other">Other</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor="address-label">Label</Label><Input id="address-label" name="label" placeholder="Home, office…" /></div><div className="flex flex-col gap-2"><Label htmlFor="address-recipient">Recipient</Label><Input id="address-recipient" name="recipientName" defaultValue={customer.fullName} /></div><div className="flex flex-col gap-2"><Label htmlFor="address-phone">Delivery phone</Label><Input id="address-phone" name="phone" defaultValue={customer.primaryPhone ?? ''} /></div><div className="flex flex-col gap-2 sm:col-span-2"><Label htmlFor="address-line">Address</Label><Input id="address-line" name="addressLine1" required /></div>{['area','city','state','postalCode'].map((field) => <div key={field} className="flex flex-col gap-2"><Label htmlFor={`address-${field}`}>{field === 'postalCode' ? 'Postal code' : field[0].toUpperCase() + field.slice(1)}</Label><Input id={`address-${field}`} name={field} /></div>)}</div><label className="flex items-center gap-2 text-sm"><Switch name="isDefault" />Use as default address</label><DialogFooter><Button type="submit" disabled={addAddress.isPending}>Save address</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={dialog === 'note'} onOpenChange={(open) => setDialog(open ? 'note' : null)}><DialogContent><DialogHeader><DialogTitle>Add internal note</DialogTitle><DialogDescription>Notes are appended to history and visible only to authorized staff.</DialogDescription></DialogHeader><form onSubmit={submitNote} className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="note-body">Note</Label><Textarea id="note-body" name="body" required maxLength={2000} /></div><label className="flex items-center gap-2 text-sm"><Switch name="isPinned" />Mark important</label><DialogFooter><Button type="submit" disabled={addNote.isPending}>Add note</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={dialog === 'tag'} onOpenChange={(open) => setDialog(open ? 'tag' : null)}><DialogContent><DialogHeader><DialogTitle>Assign customer tag</DialogTitle><DialogDescription>Use a tenant-wide tag for consistent segmentation, or create one.</DialogDescription></DialogHeader><form onSubmit={submitTag} className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label>Existing tag</Label><Select name="tagId"><SelectTrigger><SelectValue placeholder="Choose a tag" /></SelectTrigger><SelectContent><SelectGroup>{tags.filter((tag) => !customer.tags.some((assigned) => assigned.id === tag.id)).map((tag) => <SelectItem key={tag.id} value={tag.id}>{tag.name}</SelectItem>)}</SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor="new-tag">Or create a tag</Label><Input id="new-tag" name="newTag" /></div><DialogFooter><Button type="submit">Assign tag</Button></DialogFooter></form></DialogContent></Dialog>

      <Dialog open={dialog === 'consent'} onOpenChange={(open) => setDialog(open ? 'consent' : null)}><DialogContent><DialogHeader><DialogTitle>Record consent decision</DialogTitle><DialogDescription>This creates a new ledger entry; it does not erase previous decisions.</DialogDescription></DialogHeader><form onSubmit={submitConsent} className="flex flex-col gap-4"><div className="flex flex-col gap-2"><Label htmlFor="consent-purpose">Purpose</Label><Input id="consent-purpose" name="purpose" placeholder="marketing_updates" required /></div><div className="grid gap-4 sm:grid-cols-2"><div className="flex flex-col gap-2"><Label>Channel</Label><Select name="channel" defaultValue="sms"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{['phone','sms','whatsapp','email'].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label>Decision</Label><Select name="granted" defaultValue="true"><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="true">Granted</SelectItem><SelectItem value="false">Revoked</SelectItem></SelectGroup></SelectContent></Select></div></div><div className="flex flex-col gap-2"><Label htmlFor="consent-source">Source</Label><Input id="consent-source" name="source" defaultValue="owner_dashboard" required /></div><DialogFooter><Button type="submit" disabled={recordConsent.isPending}>Record decision</Button></DialogFooter></form></DialogContent></Dialog>

      <AlertDialog open={archiveOpen} onOpenChange={setArchiveOpen}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Archive {customer.fullName}?</AlertDialogTitle><AlertDialogDescription>Archiving is rejected while any booking remains operational. Historical bookings and financial evidence are retained.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={() => archive.mutate(id, { onSuccess: () => router.push('/dashboard/customers') })}>Archive customer</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    </main>
  );
}
